# Generated by Django 2.2.19 on 2021-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباره ی ما', 'verbose_name_plural': 'درباره ی ما'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date',), 'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterField(
            model_name='about',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
