# Generated by Django 2.2.19 on 2021-03-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_auto_20210308_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
