# Generated by Django 2.2.19 on 2021-03-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0003_auto_20210308_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
