# Generated by Django 2.2.19 on 2021-03-10 11:02

from django.db import migrations, models
import django.db.models.deletion
import gig.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=20, verbose_name='پیوست')),
                ('cost', models.IntegerField(verbose_name='قیمت')),
                ('description', models.TextField(max_length=5000, verbose_name='توضیحات')),
                ('sell_count', models.IntegerField(default=0, verbose_name='تعداد دفعات فروش')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gig.models.get_name, verbose_name='تصویر')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Field', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'گیگ',
                'verbose_name_plural': 'گیگ ها',
                'ordering': ('-create',),
            },
        ),
    ]
