# Generated by Django 2.2.19 on 2021-02-26 11:20

from django.db import migrations, models
import gig.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('cost', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('sell_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gig.models.get_name)),
            ],
        ),
    ]
