# Generated by Django 2.2.19 on 2021-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User bio', max_length=3000, null=True, verbose_name='بیوگرافی')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('skills', models.ManyToManyField(blank=True, default='نامشخص', help_text='Choose Your Skills', to='category.Skills', verbose_name='مهارت ها')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
