# Generated by Django 2.2.18 on 2021-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='User bio', max_length=1000)),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Birth')),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, help_text='Choose Your Skills', to='proFile.Skills')),
            ],
        ),
    ]
