# Generated by Django 2.2.17 on 2021-02-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proFile', '0004_auto_20210226_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ForeignKey(blank=True, default=None, help_text='Choose Your Skills', on_delete=django.db.models.deletion.CASCADE, to='proFile.Skills'),
        ),
    ]
