# Generated by Django 2.2.17 on 2021-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proFile', '0005_auto_20210226_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Choose Your Skills', to='proFile.Skills'),
        ),
    ]
