# Generated by Django 2.2.19 on 2021-03-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-publish',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
