# Generated by Django 2.2.19 on 2021-03-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_replycomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='پاسخ'),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
