# Generated by Django 2.2.19 on 2021-03-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20210312_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='reply_to',
        ),
    ]
