# Generated by Django 2.2.19 on 2021-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20210312_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=models.DateTimeField(null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
