# Generated by Django 2.2.19 on 2021-03-10 11:02

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('date_of_payment', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
            ],
            options={
                'verbose_name': 'سبد خرید کاربر',
                'verbose_name_plural': 'سبد های خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت گیگ')),
                ('deadline', models.IntegerField(verbose_name='مهلت تحویل سفارش')),
            ],
            options={
                'verbose_name': 'جزپیات محصول',
                'verbose_name_plural': 'جزپیات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.BooleanField(default=False, verbose_name='منقضی شده / نشده')),
                ('delivery_status', models.BooleanField(default=False, verbose_name='وضعیت/ تحویل')),
                ('date_of_transaction', models.DateTimeField(verbose_name='زمان انجام معامله')),
                ('deadline', models.DateTimeField(verbose_name='مهلت تحویل')),
                ('file', models.FileField(blank=True, null=True, upload_to=order.models.get_name, verbose_name='فایل ارسالی')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
            },
        ),
    ]
